version: '3.8'

services:
  cache:
    image: redis:alpine
    restart: always
  api:
    image: backend_app
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
      args:
        version: 2020
    ports:
      - '80:5000'
    restart: always
