ARG PYTHONVERSION=3
FROM python:$PYTHONVERSION-alpine
ARG PYTHONVERSION=3
RUN echo $PYTHONVERSION
LABEL python_version=$PYTHONVERSION \
    description="Образ, на основе Alpine \
с установленным интерпретатором Python $PYTHONVERSION"
