"""empty message

Revision ID: 5fb6cf91f9cc
Revises: 
Create Date: 2020-06-28 19:26:24.201777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fb6cf91f9cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finish_time', sa.DateTime(), nullable=True),
    sa.Column('elapsed_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_results_elapsed_time'), 'results', ['elapsed_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_results_elapsed_time'), table_name='results')
    op.drop_table('results')
    # ### end Alembic commands ###
