version: '3.8'

services:
  cache:
    image: redis:alpine
    restart: always
  api:
    image: backend_app
    build: ./backend
    environment:
      DEBUG_MODE: "true"
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    ports:
      - "80:5000"
    restart: always
