version: '3'

services:
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/data
  app:
    build: .
    ports:
      - "80:5000"
    volumes:
      - ./:/app
    depends_on:
      - redis
    restart: always

volumes:
  redis_data:
